### ISSUE TITLE
Allow capability to cancel a job via id

### ISSUE THREAD

**Issue by prabirshrestha** [ZeroAssumptions/aide-de-camp#6]
Could be useful when the Job is scheduled in the future and hasn’t run so would want to cancel it so it never runs. 

As for a job that is already running but takes long time to finish one might need to manually check for is_cancel_reqested() and stop processing further. Long running process such as video encoding/decoding is a sample use case for this.

**Comment by andoriyu** [comment]
@prabirshrestha First one is easy to implement, honestly surprised that I've missed it in the API.

The second one is a bit harder and will require some changes to how worker operates. Probably not going to support this until later.
